name: Run Unit Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          add-apt-repository ppa:ethereum/ethereum
          apt-get update
          apt-get install solc
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests with pytest
        run: pytest
        env:
          PYTHONPATH: "."
