name: sonarqube
on:
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarQube Scan
      uses: block42-blockchain-company/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_ADDRESS }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        dns: sonarqube.b42.tech
        port: 443
